### ISSUE TITLE
Update to Reactstrap

### ISSUE THREAD

**Issue by ghost** [rederlyhq/frontend#19]
Currently, we're using react-bootstrap, which is a component library that is compatible with Bootstrap v3. It is not, however, compatible with the latest versions of React and uses deprecated functionality. Switching to reactstrap should be as simple as changing the import statements since component names and functionality should be mostly consistent.

**Comment by gbhojraj** [comment]
Looks like I misunderstood the support react-bootstrap has. Their website has Bootstrap 4 listed with 1.0.1, which we should be using. The comparison with reactstrap is less clear (https://stackoverflow.com/questions/56061590/what-is-difference-between-reactstrap-and-react-bootstrap)

Personally, I would prefer ripping out Bootstrap and using a better set of form tools and writing custom CSS around them (https://react-hook-form.com/api/ was my initial goto, but I couldn't get it working with the bootstrap component system, so I dropped it and went with bare bootstrap.)

**Comment by red-tt-bear** [comment]
We switched to material UI, need to remove react strap entirely as it phases out
