### ISSUE TITLE
Problem rendering for instructor vs student

### ISSUE THREAD

**Issue by doombot-exe** [rederlyhq/frontend#59]
Problems should be requested from the renderer with the template : 'single' in order to prevent the "show correct answers" button from appearing to students.

We will also need to handle renderer requests for instructors differently from students? The principle reason for this is in how it applies to 'scaffold.pl' problems, which look at user permissions to decide whether to "lock down" parts of the problem.

**Comment by drdrew42** [comment]
For now, the submit button issue has been mostly resolved - leaving the "render_as_student" vs "render_as_instructor" still to be addressed.

**Comment by doombot-exe** [comment]
actually - all problem rendering requests are passed through backend

refer to rederly/backend#62
